### ISSUE TITLE
:bug: bug(?) report

### ISSUE THREAD

**Issue by maguman** [tadak-web/tadak-web.github.io#1]
안녕하세요.

저는 몇 달 전부터 이 웹사이트를 잘 이용해 왔습니다.
증상은 한 두 달 전부터인가 갑자기 language 선택창에 옵션이 보이지 않았어요.
링크된 동영상에는 여러 언어 자막(자동생성이 아닌)이 있지만 옵션이 선택되지 않으니 Dictation으로 넘어갈 수가 없습니다.
제가 사용했던 동영상 링크는 www.youtube.com/watch?v=zYk0GH5iFYI  입니다.
아래 증상에 대한 캡쳐화면도 첨부합니다.
감사합니다.

![image](https://user-images.githubusercontent.com/9715195/143767921-667fda3e-6b97-4db9-a023-87fdf0f5814b.png)

**Comment by tadak-web** [comment]
안녕하세요.

Youtube API가 변경되어 기존의 사용하던 방법으로 리스트를 받아올 수 없는 문제가 생겼습니다.
Youtube 자막 리스트를 받아 올 수 있는 API를 제작하여 오류를 수정하였습니다.
추가적으로 자동 생성 자막 또한 사용 가능하도록 하였습니다.

**Comment by maguman** [comment]
👍  우와우 API 업데이트 뿐만 아니라 **자동 생성 자막** 까지 사용가능하도록 업그레이드 하셨네요. 
배려와 노고에 진심으로 감사 드립니다. 🙏
