### ISSUE TITLE
기능 추가 관련 문의드립니다

### ISSUE THREAD

**Issue by zion830** [tadak-web/tadak-web.github.io#2]
안녕하세요.
딕테이션으로 구글링 하다가 우연히 이 서비스를 발견해서 유용하게 잘 사용하고 있습니다.
history에서 마지막으로 설정했던 원본/번역 언어도 같이 저장되는 기능이 생기면 좋을 거 같아 여기에 의견 남겨봅니다.
좋은 서비스 만들어주셔서 감사합니다.

**Comment by josw123** [comment]
사용해 주셔서 감사합니다.

요청하신 기능을 추가하도록 하겠습니다.

**Comment by zion830** [comment]
@josw123 흔쾌히 의견 받아주셔서 감사합니다!
사용법도 직관적이고 정말 짱 좋은 서비스입니다 👍
