### ISSUE TITLE
버그 제보

### ISSUE THREAD

**Issue by zion830** [tadak-web/tadak-web.github.io#3]
<img width="517" alt="스크린샷 2022-08-25 오후 11 09 19" src="https://user-images.githubusercontent.com/35446215/186687718-e34e9e3c-aabe-4855-b3cf-207d300d1e86.png">
안녕하세요.
여러개의 영상을 넣어봤는데 lang은 빈칸, trans엔 None만 뜨는 버그가 있어서 제보드립니다!

**Comment by josw123** [comment]
API 서버가 죽어서 생긴 문제입니다.
현재 다시 작동시켜 동작 중입니다.
