### ISSUE TITLE
버그 제보

### ISSUE THREAD

**Issue by zion830** [tadak-web/tadak-web.github.io#4]
안녕하세요
자꾸 이것 저것 해달라 요청드려 죄송합니다..
언어를 고를때 이렇게 나오는 현상이 있어 제보드립니다!!
* 환경 : Mac OS, Chrome
<img width="1359" alt="스크린샷 2022-09-16 오전 11 48 49" src="https://user-images.githubusercontent.com/35446215/190546043-e4e236cb-d41b-4672-93f6-26d524aa59bc.png">
<img width="1184" alt="스크린샷 2022-09-16 오전 11 49 01" src="https://user-images.githubusercontent.com/35446215/190546061-c63426ac-4e2b-4d21-9bc2-38fa884d8a1f.png">

**Comment by josw123** [comment]
안녕하세요.

Youtube API 데이터를 받아오는 클라우드 서버 IP가
중동쪽으로 설정되어서 그런것 같습니다.

해당 코드를 수정하여 오늘중으로 수정하도록 하겠습니다.

**Comment by josw123** [comment]
방금전 수정하여 영문으로 표시되도록 하였습니다.
